### ISSUE TITLE
Enable to edit profiles O.O

### ISSUE THREAD

**Issue by teidova21** [X1nto/Mauth#11]
Tapping the pen icon doesnt open the app modification screen so i cant put cute icons upon apps already registered.

PS : the three left bottom seems to do nothing as well tho that's maybe WIP idk :x (can't find on the roadmap)
PS2 : I'm in love with your design 😍

**Comment by teidova21** [comment]
OK i'm blind i didn't see the organization category -_-

**Comment by X1nto** [comment]
Keeping this reopened just to track the progress
