### ISSUE TITLE
settings button not working

### ISSUE THREAD

**Issue by anikethjkv** [X1nto/Mauth#14]
Hello I found your app on Fdroid. It is great. but the settings button is not working and also the edit button for name and label is not working after creation. I am loving your app. I want to switch away from Microsoft authenticator. So please do update this issue. Also if you have rise up mail can you send me an invite

**Comment by X1nto** [comment]
The app is still in its early stage, which means not everything is implemented yet. The edit button was added in version 0.4.0 which is not yet available on F-Droid and might take some days to arrive there. If you want, you can download the version from GitHub releases, but keep in mind that you won't be able to update the GitHub version from F-Droid

**Comment by anikethjkv** [comment]
Thanks Very much I appreciate your hard work and dedication towards the app. I will wait. I want to distance my self from big tech. Thanks very much.
