### ISSUE TITLE
[Question] F-droid update delay ?

### ISSUE THREAD

**Issue by teidova21** [X1nto/Mauth#15]
Hello,

What is the delay for fdroid updates, as the last one isn't available there yet ?

Thanks

**Comment by X1nto** [comment]
I don't know, the last time I opened a PR on their fdroiddata repo, they told me that PRs were unnecessary because the bot auto-updated every app based on the GitHub releases. I'll wait another day or 2 and open a PR manually on their data repo

**Comment by X1nto** [comment]
Update: it seems like the bot [did indeed auto-update Mauth](https://gitlab.com/fdroid/fdroiddata/-/commit/63bc07030ed661efcbe497ac667f07ebd1e87166). Expect the app to be available either tomorrow or after tomorrow

**Comment by Hedronmx** [comment]
Updates are still delayed! Last version is 0.4 on fdroid

**Comment by X1nto** [comment]
There's nothing I can do about that.
https://f-droid.org/en/docs/FAQ_-_App_Developers/#ive-published-a-new-release-why-is-it-not-in-the-repository
![image](https://user-images.githubusercontent.com/48173186/225848977-6a7faaed-b3cb-4fb9-90a4-a0417e20bd4e.png)

**Comment by Hedronmx** [comment]
Not to be rude or anything but the last update on FDroid was on 10/22/22, thats more than a few days... There has to be a problem doesn't it?

**Comment by X1nto** [comment]
But the version after that was released about 2 days ago?

**Comment by X1nto** [comment]
There was a 6-month gap between v0.4.0 and v0.5.0

**Comment by Hedronmx** [comment]
Ooh I see!! My bad, did not check releases. Thanks for the quick replies!
