### ISSUE TITLE
Theme settings for the liking. (GitHub Mobile tags does not appear)

### ISSUE THREAD

**Issue by ian1ilych** [X1nto/Mauth#29]
The app may be more customizable with themes to make it to whatever liking you want for Material You.

For example:

Enable/Disable Wallpaper Theme
or
Choose any color for the theming. (Works when Wallpaper Theme is disabled)
or when to not least: Light/Dark Mode.

**Comment by X1nto** [comment]
Sure I guess but what does GitHub Mobile has to do with this?

**Comment by ian1ilych** [comment]
Honesttly, GitHub Mobike is an offial GitHub app to download apps and use it as a 2FA, and anything.

And well, i need to add tags to appear. Ok?

**Comment by X1nto** [comment]
I know what GitHub Mobile is, I use it myself, it's just a GitHub client. What I'm asking is what tags you're talking about.

**Comment by X1nto** [comment]
Added in v0.8.0
