### ISSUE TITLE
Implement transparent Navigation Bar

### ISSUE THREAD

**Issue by electr1fy0** [X1nto/Mauth#31]
### **How it is v/s How it should be:**
![Screenshot_20230218-205217](https://user-images.githubusercontent.com/87616300/219873907-527e1e4c-6d8b-42f8-b6ce-6ee4fedf5398.png)
![Screenshot_20230218-205325](https://user-images.githubusercontent.com/87616300/219873910-55597cfa-f1fb-49be-a32e-520391378a71.png)

**Comment by X1nto** [comment]
Oh, that's a nice suggestion! Definitely coming in the next release.

**Comment by X1nto** [comment]
Added in v0.5.0

**Comment by zoroya1** [comment]
>  ### **How it is v/s How it should be:**
> ![Screenshot_20230218-205217](https://user-images.githubusercontent.com/87616300/219873907-527e1e4c-6d8b-42f8-b6ce-6ee4fedf5398.png)
> ![Screenshot_20230218-205325](https://user-images.githubusercontent.com/87616300/219873910-55597cfa-f1fb-49be-a32e-520391378a71.png)
> 

Which task app is this ? Looks so nice 🤩

**Comment by electr1fy0** [comment]
Google Tasks.

It got updated with Material You in Feb.
One of the few apps done right by Google.
