### ISSUE TITLE
App performance is really bad

### ISSUE THREAD

**Issue by T8RIN** [X1nto/Mauth#33]
App lags on every action, working with it really terrible, i have not really slow device

Snapdragon 855, Android 10

**Comment by T8RIN** [comment]
https://user-images.githubusercontent.com/52178347/225819915-f48b8570-ac83-41ab-a21c-de086be0ef6b.mp4

**Comment by X1nto** [comment]
That's weird because I specifically optimized the latest versions and I don't have any lags. Also, why does your account card have so many digits? And are you using the latest version? Make sure that it's not a debug build too.

**Comment by T8RIN** [comment]
I downloaded your release apk👀

**Comment by T8RIN** [comment]
I've set sha512, and some digits for the test)

**Comment by T8RIN** [comment]
But, if i want to generate so?

**Comment by T8RIN** [comment]
Maybe you should add some caution, that using so many numbers may be unstable

**Comment by X1nto** [comment]
I think it's better to limit the digits instead. I'll look into the HOTP/TOTP RFCs to see if they have any limits.

**Comment by X1nto** [comment]
Thanks for the report

**Comment by T8RIN** [comment]
> I don't understand why on earth you want to generate a code with 70000 digits

Ok, maybe the user did it accidentally and then he occured this lags

**Comment by X1nto** [comment]
Which is why I'll set a limit in the next release

**Comment by T8RIN** [comment]
> I think it's better to limit the digits instead. I'll look into the HOTP/TOTP RFCs to see if they have any limits.

Also a good option, the main thing is to warn that such actions can break the application

**Comment by T8RIN** [comment]
> I think it's better to limit the digits instead. I'll look into the HOTP/TOTP RFCs to see if they have any limits.

Also a good option, the main thing is to warn that such actions can break the application 👀

**Comment by X1nto** [comment]
Yep, got it
