### ISSUE TITLE
Saving empty secret bug 

### ISSUE THREAD

**Issue by T8RIN** [X1nto/Mauth#34]
Why app allows me to save empty secret? It brokes app forever, on every launch i get the crash below

![Screenshot_2023-03-17-21-10-04-156_com.miui.bugreport.jpg](https://user-images.githubusercontent.com/52178347/225985167-b012b1dd-6f85-47ab-8b76-b55b183fa756.jpg)

**Comment by T8RIN** [comment]
As you can see save button gets enabled even when entering only the name of the secret
![Screenshot_2023-03-17-21-12-03-580_com.xinto.mauth.jpg](https://user-images.githubusercontent.com/52178347/225985402-635a875a-92bd-4f40-9293-1de7b9ea9914.jpg)

**Comment by X1nto** [comment]
Thanks for the report. It seems like I forgot to update the variable names when duplicating the checks. I'll re-release 0.5.2.

**Comment by T8RIN** [comment]
:)
