### ISSUE TITLE
how to use this app

### ISSUE THREAD

**Issue by Uchiha-SR** [X1nto/Mauth#47]
how do i use this app?. i  manually added my github's credentials but dont know how to use it

**Comment by X1nto** [comment]
Do you know what 2 Factor Authentication is?

**Comment by Uchiha-SR** [comment]
yes.  after entering password. you also have to enter another pin you receive on your mobile number or app.

**Comment by X1nto** [comment]
Yes. You use Mauth with the exact same purpose. You get a prompt to enter the 2FA code, you open Mauth, copy the code, and paste it in the respective app.

**Comment by Uchiha-SR** [comment]
i actually scanned the qr code with this app that you get while setting up the 2fa on github but i am not getting prompt to enter the pin that is generated on app

if it is possible for you to give me step by step guide. please

**Comment by X1nto** [comment]
That's not something I can help with. The enter prompt is dependent on the website itself, not Mauth. Mauth does not send data to any server so it's not possible for websites to know whether you scanned a QR code or not.
