### ISSUE TITLE
Suggestion: option to import and export authentication

### ISSUE THREAD

**Issue by franco27** [X1nto/Mauth#52]
In your application, it is unfortunate that one cannot export and import their authentications or the data from your application to a file, in order to be able to restore them later.

**Comment by X1nto** [comment]
Duplicate of #10

**Comment by franco27** [comment]
The feature I suggested to you is not for importing a file from another authentication application, but for restoring a file that contains the authentications of your application in order to restore them in another installation or on another device. 
The purpose is to retrieve them in your application.
