### ISSUE TITLE
Here's a review of mine.

### ISSUE THREAD

**Issue by redcatxus** [X1nto/Mauth#54]
This app, providing the use of Two Factor Authentication (2FA), gives you some features that I've never seen before. Type (Hotp & Totp) and the algorithms, I have no clue what those are, but it could be useful for those whose got the knowledge.
It's got the Material Design 3 from Google, which is what I've been looking for.
It provides something that I've been searching for as well: the ability to actually edit the whole thing—by the thing I mean the "accounts"—for an example, all (if not, most) authenticator apps only allows you to change its label and icon. I can edit the client secret without having to delete the previous one and create a brand new one.
overall, a 5 star from me :D

**Comment by X1nto** [comment]
Thank you, but issues aren't really the place for reviews :)
