### ISSUE TITLE
Consolidate Info Page Content into Settings Page.

### ISSUE THREAD

**Issue by git10700** [X1nto/Mauth#65]
I think it would be more intuitive to have a single 'Settings' button rather than a menu with only two items. Additionally, it would be beneficial to consolidate the information currently presented on the 'Info' page into the 'Settings' page, eliminating the need for a separate 'Info' page.

**Comment by X1nto** [comment]
The 3-dot menu will contain more items in the future and storing every single one of them in the bottom bar will make it ugly. The application info doesn't belong in settings, as those are 2 separate pages. Both of them will contain more stuff in the future, so merging them is not an option.
